# -*- coding: utf-8 -*-
"""Task.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Afo3BV4iXSJY5nVNu3BKktmCrn8RTK2I

# ***AI/ML Task: Voice-Based Cognitive Decline Pattern Detection***

1. Install Required Packages
"""

# Run these once in the notebook or install them via terminal before starting
!pip install librosa pydub SpeechRecognition webrtcvad
!pip install nltk spacy scikit-learn matplotlib seaborn pandas numpy
!python -m nltk.downloader all
!python -m spacy download en_core_web_sm

""" 2. Import Libraries and Setup"""

import librosa
import librosa.display
import speech_recognition as sr
from pydub import AudioSegment
import webrtcvad

import nltk
import spacy
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import IsolationForest

import matplotlib.pyplot as plt
import seaborn as sns
import os
import warnings
warnings.filterwarnings('ignore')

# Load NLP models
nlp = spacy.load("en_core_web_sm")
nltk.download("punkt")

"""**3. Upload & List Audio Files**"""

from google.colab import files
uploaded = files.upload()  # Select 5–10 .wav files

os.makedirs("voice_clips", exist_ok=True)

for filename in uploaded:
    os.rename(filename, f"voice_clips/{filename}")

# List files
AUDIO_DIR = "voice_clips"
audio_files = [f for f in os.listdir(AUDIO_DIR) if f.endswith('.wav')]
print("Uploaded files:", audio_files)

"""**`** 4. Transcribe Audio to Text**`**"""

recognizer = sr.Recognizer()

def transcribe_audio(file_path):
    with sr.AudioFile(file_path) as source:
        audio = recognizer.record(source)
        try:
            return recognizer.recognize_google(audio)
        except sr.UnknownValueError:
            return ""
        except sr.RequestError:
            return ""

transcriptions = {}
for f in audio_files:
    path = os.path.join(AUDIO_DIR, f)
    transcriptions[f] = transcribe_audio(path)

# View transcripts
for fname, text in transcriptions.items():
    print(f"\n{fname}: {text}")

"""**5. Extract Audio & NLP Features**"""

import re
import librosa
import numpy as np
import speech_recognition as sr

def extract_audio_features(file_path, text):
    # Load the audio
    y, sr = librosa.load(file_path)
    duration = librosa.get_duration(y=y, sr=sr)

    # Basic features
    speech_rate = len(text.split()) / duration if duration > 0 else 0
    pitch = librosa.yin(y, fmin=50, fmax=300)
    pitch_var = np.std(pitch)

    # Hesitation detection
    hesitation_words = ['um', 'uh', 'erm', 'ah', 'like', 'you know', 'so']
    hesitations = sum(len(re.findall(r'\b' + hw + r'\b', text.lower())) for hw in hesitation_words)

    # Pause detection: Improved method using word count and sentence structure
    # Using a basic idea that pauses usually happen between punctuation marks or long gaps between words.
    pauses = sum(1 for word in text.split() if word in ['.', ',', '?', '!', '...', '—'])

    # Return the feature set
    return {
        'speech_rate': speech_rate,
        'pitch_var': pitch_var,
        'hesitations': hesitations,
        'pauses': pauses,
        'word_count': len(text.split())
    }

# Example usage for extracting features from audio files
feature_data = []
for f in audio_files:
    path = os.path.join(AUDIO_DIR, f)
    text = transcriptions[f]
    features = extract_audio_features(path, text)
    features['file'] = f
    feature_data.append(features)

# Convert the feature data to a DataFrame
df_features = pd.DataFrame(feature_data)
df_features.set_index('file', inplace=True)
df_features

"""**6. Anomaly Detection using Isolation Forest**"""

# Perform scaling on features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(df_features)

# Fit the IsolationForest model
model = IsolationForest(contamination=0.2, random_state=42)
df_features['anomaly_score'] = model.fit_predict(X_scaled)  # This adds the 'anomaly_score' column
df_features['risk'] = df_features['anomaly_score'].apply(lambda x: 'At Risk' if x == -1 else 'Normal')
df_features

"""**7. Visualization**"""

sns.pairplot(df_features, hue='risk')
plt.suptitle("Feature Distributions with Risk Tags", y=1.02)
plt.show()

print(df_features.columns)

"""**8. Optional: Risk Score Function**"""

def get_cognitive_score(audio_path):
    text = transcribe_audio(audio_path)
    features = extract_audio_features(audio_path, text)
    input_df = pd.DataFrame([features])
    input_scaled = scaler.transform(input_df)
    risk = model.predict(input_scaled)
    return "At Risk" if risk[0] == -1 else "Normal"

# Example usage:
# print(get_cognitive_score("voice_clips/sample1.wav"))
    print(get_cognitive_score("voice_clips/sample1.wav"))

"""# **Additional**

Boxplot to Visualize Feature Distributions:
"""

plt.figure(figsize=(8, 6))
sns.boxplot(data=df_features.drop(columns=['anomaly_score'], errors='ignore'))
plt.title('Feature Distribution Boxplot')
plt.show()

"""Histogram for Each Feature:"""

df_features.drop(columns=['anomaly_score'], errors='ignore').hist(figsize=(10, 8), bins=20)
plt.suptitle('Feature Distributions')
plt.show()

"""## 🧠**Voice-Based Cognitive Decline Detection – Final Report**
### 1. Most Insightful Features
- **Speech Rate**: Slower speech may correlate with cognitive stress.
- **Pitch Variability**: Low pitch variation can reflect flat or strained delivery.
- **Hesitations (um, uh)**: Increased hesitations signal uncertainty or word-recall issues.
- **Pauses**: Proxy for difficulty in sentence formulation.

### 2. ML Method Used
- **Unsupervised Model**: Isolation Forest

1.   List item
2.   List item


- **Why?**: Since labels for "at risk" vs "normal" are unavailable, we used this to identify outliers in feature space.

### 3. Results Summary
- Audio files tagged with 'At Risk' based on outlier detection.
- Pairplot shows some separation based on speech patterns and variance.

### 4. Future Improvements
- Use larger, clinically labeled datasets.
- Include more advanced features: sentiment, syntactic complexity.
- Integrate deep audio models like wav2vec or Whisper for better transcription.
- Collaborate with cognitive science experts for evaluation.

"""